config/routes.rb
Rails.application.routes.draw do
  get 'tuto/show'
  devise_for :users
  root to: 'users#playground'
  resources :users, only: [:index] do
    collection do
      get :playground
    end
  end

  resources :missions, only: [:index, :show] do
    resources :challenges, only: [:create]
  end

  resources :challenges, only: [:show] do
    post 'validate', as: :validate
    resources :questions do
      post 'validate', as: :validate, to: 'challenge_questions#validate'
      get 'new', to: 'challenge_questions#new'
    end
    get 'map', to: 'challenges#map'
    # post 'map', as: :validate, to: 'challenge_questions#validate'
    get 'score', to: 'challenges#score'
  end

  get 'map_all_challenges', to: 'challenges#map_all_challenges'

  # Route for Treasuremapp tuto
  get 'tuto/description_treasurmapp', to: 'tuto#description'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :challenges
  has_one_attached :photo

  # class method to sum the scores stored in all challenges belonging to user
  def calculate_score
    challenges.sum(:score)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # Gathers all users sorted by score (through a class method in User model)
    @users = User.all.sort_by { |user| -user.calculate_score }
  end

  def playground
    users = User.all.sort_by { |user| -user.calculate_score }
    @rank = users.index(current_user) + 1
    if @rank == 1
      @users_shortlist = users[0...3]
    else
      @users_shortlist = users[(@rank - 2)...(@rank + 1)]
    end

    @open_challenges = Challenge.where(user: current_user, status: false)
    @done_challenges = Challenge.where(user: current_user, status: true).order(score: :desc)
    @done_count = @done_challenges.count
  end
end

app/views/users/index.html.erb
<div class="main">

  <div class="banner-custom">
    <img src='https://cdn.pixabay.com/photo/2017/01/18/10/43/banner-1989514_1280.png' alt='Background Picture'>
    <div class="banner-back">
      <%= link_to "retour", missions_path %>
    </div>
  </div>
  <div class="box-avatar">
    <lottie-player src="https://assets5.lottiefiles.com/packages/lf20_xldzoar8.json" speed="1" class= "loading avatar border-red" loop autoplay></lottie-player>
  </div>

  <div class="text-map">
    <h2>Classement</h2>
  </div>

  <table class="table" id="leaderboard-table">
      <thead>
        <tr class="leaderboard-head">
          <th scope="col">Rang</th>
          <th scope="col"></th>
          <th scope="col" style="text-align: left">Utilisateur</th>
          <th scope="col">Score</th>
        </tr>
      </thead>

    <tbody>
      <% @users.each_with_index do |user, index| %>

        <% if user == current_user %>
          <tr class="rank<%= index %> custom-row row-current-user">
            <th scope="row"><%= index + 1 %></th>
            <td>
              <% if user.photo.attached? %>
                <%= cl_image_tag user.photo.key, crop: :fill, class:'avatar-small border-red' %>
              <% else %>
                <img src="https://www.splitbrain.org/_static/monsterid/monsterid.php?.png" alt="avatar" class='avatar-small border-red'>
              <% end %>
            </td>
            <td style="text-align: left"><%= user.nickname %></td>
            <td>
              <% if user.calculate_score  %>
                <%= user.calculate_score %>
              <% else %>
                0
              <% end %>
            </td>
          </tr>
        <% else %>
          <tr class="rank<%= index %>">
            <th scope="row"><%= index + 1 %></th>
            <td>
              <% if user.photo.attached? %>
                <%= cl_image_tag user.photo.key, crop: :fill, class:'avatar-small border-red' %>
              <% else %>
                <img src="https://www.splitbrain.org/_static/monsterid/monsterid.php?.png" alt="avatar" class='avatar-small border-red'>
              <% end %>
            </td>
            <td style="text-align: left"><%= user.nickname %></td>
            <% if user.calculate_score  %>
              <td><%= user.calculate_score %></td>
            <% else %>
              <td>0</td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>

  </table>
</div>

app/views/users/playground.html.erb
<div class="main">

  <div class="banner-custom">
    <img src='https://cdn.pixabay.com/photo/2017/01/18/10/43/banner-1989514_1280.png' alt=''>
    <div class="banner-button">
      <%= link_to "Mon profil",  edit_user_registration_path, class:'btn-border-white' %>
    </div>

    <div class="banner-button-left">
      <i class="fas fa-info-circle"></i>
    </div>

  </div>
  <div class="box-avatar">
    <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, crop: :fill, class:'avatar border-red' %>
    <% else %>
      <img src="https://www.splitbrain.org/_static/monsterid/monsterid.php?.png" alt="avatar" class='avatar border-red'>
    <% end %>
  </div>
  <div class="title-mission">
    <h2>Hello <%=current_user.first_name%>!</h2>
  </div>
  <hr style="width: 50%; margin-left: auto">

  <% if @done_challenges.empty? & @open_challenges.empty?  %>
    <div class="mission-icon-box">
      <h5>Tu n'as pas encore commencé de mission.</h5>
      <p>Clique vite sur ce lien pour découvrir dans quelle aventure tu peux t'embarquer</p>
      <a href="/missions" class="btn btn-red" style="color: white"> Vers les missions </a>
    </div>
  <% else %>

    <h3 style='text-align: center'>Aperçu du classement</h3>


    <div class="leaderboard mb-2 mx-2">
      <table class="table-custom">
        <tbody>
          <% @users_shortlist.each_with_index do |user, index| %>

            <% if user == current_user %>
              <tr class='custom-row row-current-user'>
                <th scope="row"><%= @rank %></th>
                <td><%= user.nickname %></td>
                <td><%= user.calculate_score %></td>
              </tr>
            <% else %>
              <%@rank != 1 ? rank = @rank - 1 : rank = @rank %>
              <tr class = "custom-row">
                <th scope="row"><%= index + rank %></th>
                <td><%= user.nickname %></td>
                <td><%= user.calculate_score %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <div class="box-button"><%= link_to "Voir plus", users_path, class:'btn-border-red' %></div>
    </div>

  <hr style="width: 50%; margin-left: auto">

    <div class="open-mission mb-4 text-center">
      <h3>Vos missions inachevées</h3>

      <div class="container-custom">
      <% @open_challenges.each do |challenge|%>

        <div class="playground-card">
          <div class="playground-card-img">
            <%= image_tag challenge.mission.photo_url, alt: "Le Wagon" %>
          </div>
          <div class="playground-card-infos">
            <div class="playground-card-infos-text">
              <h5><%= challenge.mission.name %></h5>
              <div>
                <p>📍 <%= challenge.mission.city %> </p>
                <p>🏋️‍♀️ <%= challenge.mission.difficulty %></p>
              </div>
            </div>
            <div class="playground-right-box">
              <div class="playground-card-infos-score"><%= challenge.progress %> %</div>
              <div class="btn-red playground-card-button"><%= link_to 'Reprendre', challenge_path(challenge)%></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    </div>

    <hr style="width: 50%; margin-left: auto">

    <% if @done_count >= 3 %>
      <div class="text-center">
        <h3>Vos missions terminées</h3>

        <div class="done-mission">
          <div class="podium">
            <div class="podium-shape">
              <div id="shape-second" class="podium-step-box">
                <a href="/challenges/<%= @done_challenges[1].id %>/score">
                  <p class="medal">🥈</p>
                  <p class="mission-name"><%= @done_challenges[1].mission.name %></p>
                  <p class="mission-score"><%= @done_challenges[1].score %></p>
                </a>
              </div>

              <div id="shape-first" class="podium-step-box">
                <a href="/challenges/<%= @done_challenges[0].id %>/score">
                  <p class="medal">🥇</p>
                  <p class="mission-name"><%= @done_challenges[0].mission.name %></p>
                  <p class="mission-score"><%= @done_challenges[0].score %></p>
                </a>
              </div>

              <div id="shape-third" class="podium-step-box">
                <a href="/challenges/<%= @done_challenges[2].id %>/score">
                  <p class="medal">🥉</p>
                  <p class="mission-name"><%= @done_challenges[2].mission.name %> <br></p>
                  <p class="mission-score"><%= @done_challenges[2].score %></p>
                </a>
              </div>
            </div>
          </div>
          <% if @done_count >= 4 %>
            <table class="table-podium">
              <tbody>
                <% @done_challenges[3...@done_count].each_with_index do |challenge, index| %>
                  <tr class = "podium-row">
                    <th scope="row"><%= index + 4 %></th>
                    <td><a href="/challenges/<%= challenge.id %>/score"><%= challenge.mission.name%></a></td>
                    <td><%= challenge.score %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>


    <% elsif @done_count >= 1 %>
      <div class="text-center">
        <h3>Vos missions terminées</h3>
        <table class="table-podium">
          <tbody>
            <% @done_challenges.each_with_index do |challenge, index| %>
              <tr class = "podium-row">
                <th scope="row"><%= index + 1 %></th>
                <td><a href="/challenges/<%= challenge.id %>/score"><%= challenge.mission.name%></a></td>
                <td><%= challenge.score %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    <% else %>
      <div class='playground-box text-center'>
        <p>Vous n'avez pas encore terminé de mission</p>
        <%= link_to "Mission", missions_path, class:'btn btn-red', style:'color: white;' %>
      </div>
    <% end %>

  <% end %>
</div>