config/routes.rb
Rails.application.routes.draw do
  get 'tuto/show'
  devise_for :users
  root to: 'users#playground'
  resources :users, only: [:index] do
    collection do
      get :playground
    end
  end

  resources :missions, only: [:index, :show] do
    resources :challenges, only: [:create]
  end

  resources :challenges, only: [:show] do
    post 'validate', as: :validate
    resources :questions do
      post 'validate', as: :validate, to: 'challenge_questions#validate'
      get 'new', to: 'challenge_questions#new'
    end
    get 'map', to: 'challenges#map'
    # post 'map', as: :validate, to: 'challenge_questions#validate'
    get 'score', to: 'challenges#score'
  end

  get 'map_all_challenges', to: 'challenges#map_all_challenges'

  # Route for Treasuremapp tuto
  get 'tuto/description_treasurmapp', to: 'tuto#description'
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :user
  belongs_to :mission
  has_many :challenge_questions
  attr_accessor :long, :lat

  BONUS = {
    'facile' => 0.1,
    'moyen' => 0.3,
    'difficile' => 0.5
  }

  def progress
    nb_questions = mission.questions.count + 1
    true_questions = challenge_questions.where(status: true).count
    return 0 if nb_questions.zero?

    (true_questions / nb_questions.to_f * 100).to_i
  end

  def calculate_score
    # retrieve parameters (question answered, nb of guesses etc.)
    nb_question_answered = challenge_questions.where(status: true).count
    nb_questions_guess = challenge_questions.map { |question| question[:answer_counter] }.sum
    bonus = BONUS[mission.difficulty.downcase]
    status ? end_mission = 1 : end_mission = 0

    pt_q_answered = 50
    pt_q_guess = -5
    pt_final_guess = -15
    pt_end_mission = 200

    # points per entry
    final_q_answered = pt_q_answered * nb_question_answered
    final_q_guess = pt_q_guess * (nb_questions_guess - nb_question_answered)
    if secret_counter.positive?
      final_location_guess = pt_final_guess * (secret_counter - 1)
    else
      final_location_guess = 0
    end
    final_end_mission = pt_end_mission * end_mission

    # calculation for score
    score = (final_q_answered + final_q_guess + final_location_guess + final_end_mission)
    score_bonus = (score * bonus).to_i
    final_score = score + score_bonus
    # @time = challenge.updated_at.strftime("%d-%m-%Y %H:%M:%S") - challenge.created_at.strftime("%d-%m-%Y %H:%M:%S")

    # prepare hash
    {
      question_answered: nb_question_answered,
      question_points: pt_q_answered,
      score_questions: final_q_answered,
      question_guess: nb_questions_guess,
      guess_malus: pt_q_guess,
      score_guess: final_q_guess,
      final_guess_malus: pt_final_guess,
      final_guess: secret_counter,
      score_final_guess: final_location_guess,
      mission_done: status,
      score_end_mission: pt_end_mission,
      mission_points: final_end_mission,
      final_score: final_score,
      mission_difficulty: mission.difficulty,
      bonus: bonus,
      bonus_points: score_bonus
    }
  end

end

app/controllers/challenge_controller.rb
class ChallengeController < ApplicationController
  def show
  end

  def new
  end

  def create
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def show
    @challenge = Challenge.find(params[:id])
  end

  def new
    @question = Question.find(params[:question_id])
    @challenge = Challenge.find(params[:challenge_id])
    @challenge_question = ChallengeQuestion.new
  end

  def map
    @challenge = Challenge.find(params[:challenge_id])
    @markers = @challenge.mission.questions.map do |question|
      @challenge_question = ChallengeQuestion.find_by(question: question, challenge: @challenge)
      @challenge_question = ChallengeQuestion.new if @challenge_question.nil?
      {
        lat: question.lat,
        lng: question.lng,
        status: @challenge_question.status,
        info_window: render_to_string(partial: "popup_map", locals: { question: question, challenge: @challenge, challenge_question: @challenge_question })
      }
    end

    @questions = @challenge.mission.questions.map do |question|
      question.question
    end
  end

  def map_all_challenges
    @challenge_open = Challenge.where(user: current_user, status: false)

    @markers = []
    @challenge_open.each do |challenge|
      challenge.mission.questions.each do |question|
        @challenge_question = ChallengeQuestion.find_by(question: question, challenge: challenge)
        p "*************************"
        p challenge.inspect
        p question.inspect
        @challenge_question = ChallengeQuestion.new if @challenge_question.nil?
        @markers << {
          lat: question.lat,
          lng: question.lng,
          status: @challenge_question.status,
          info_window: render_to_string(partial: "popup_map_all", locals: { question: question, challenge: challenge, challenge_question: @challenge_question })
        }
      end
      @questions = challenge.mission.questions.each do |question|
      question.question
    end
    end
    #redirect_to challenge_score_path(challenge)
end



  def create
    challenge = Challenge.new
    challenge.user = current_user
    challenge.mission = Mission.find(params[:mission_id])
    challenge.save
    redirect_to challenge_path(challenge)
  end

  # Geolocalisation validation
  def validate
    challenge = Challenge.find(params[:challenge_id])
    mission_id = challenge.mission_id

    # place from mission
    latitude = Mission.find(mission_id).lat
    longitude = Mission.find(mission_id).lng

    place = [latitude, longitude]
    delta = 0.001000
    # user_lat = 46.505406
    user_lat = params[:lat]
    # user_long = 6.641385
    user_long = params[:lon]

    # test = user_lat.between?(place[0] - delta, place[0] + delta)
    if user_lat.between?(place[0] - delta, place[0] + delta) && user_long.between?(place[1] - delta, place[1] + delta)
      challenge.status = true
      challenge.score = challenge.calculate_score[:final_score]
      challenge.save
      render json: { location: challenge_score_path(challenge) }
    else
      flash[:falsy] = "Oups! Il semblerait que ce ne soit pas le bon endroit, essayez encore!"
      render json: { location: challenge_path(challenge) }
    end
  end

  def score
    @challenge = Challenge.find(params[:challenge_id])
  end

  private

  def questions_params
    params.require(:question).permit(:lat, :lng)
  end

end

app/views/challenges/_popup_map.html.erb
<div class="map-popup">
  <div style="height: 50px;" class="mb-3">
    <lottie-player src="https://assets2.lottiefiles.com/packages/lf20_y37xuqq6.json" speed="1" loop autoplay></lottie-player>
  </div>
  <% if challenge_question.status %>
    <div class="question-box">
      <p>Bravo! La réponse à:</p>
      <p class="question-text"><%= challenge_question.question.question %></p>
      <p>etait: </p>
      <p class="question-text"><%= challenge_question.question.answer %></p>
    </div>
      <%= link_to 'voir l\'indice débloqué', challenge_path(challenge), class: "btn-border-red"%>
  <% else %>
    <p class="question mb-3">
      <%= question.question %>
    </p>
    <%= simple_form_for challenge_question, method: :post, url: challenge_question_validate_path(challenge, question), html: { autocomplete: 'off' } do |f| %>
      <%= f.input :guess, label: false %>
      <%= f.submit "Valider", class: "btn-red" %>
    <% end %>
  <% end %>
</div>

app/views/challenges/_popup_map_all.html.erb
<div class="map-popup">
  <% if challenge_question.status %>
    <p>Bravo, vous avez déjà trouvé la bonne réponse à cette question!</p>
  <% else %>
    <div style="height: 50px;" class="mb-3">
    <lottie-player src="https://assets2.lottiefiles.com/packages/lf20_y37xuqq6.json" speed="1" loop autoplay></lottie-player>
  </div>
    <p class="question">
      <%= question.question %>
    </p>
    <%= simple_form_for challenge_question, method: :post, url: challenge_question_validate_path(challenge, question), html: { autocomplete: 'off' } do |f| %>
      <%= f.input :guess, label: false %>
      <%= f.hidden_field :redirect, value: "all_map" %>
      <%= f.submit "Valider", class: "btn-red" %>
    <% end %>
  <% end %>
</div>

app/views/challenges/create.html.erb
<h1>Challenge#create</h1>
<p>Find me in app/views/challenge/create.html.erb</p>

app/views/challenges/info_window.html.erb
<h1>Hola!</h1>

app/views/challenges/map.html.erb
<div class="banner-back-red">
    <%= link_to "retour", challenge_path(@challenge) %>
</div>
<div id="map" style="width:100%; height: 100vh;"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      data-markers="<%= @markers.to_json %>">
</div>

app/views/challenges/map_all_challenges.html.erb
<div class="banner-back-border-red">
    <%= link_to "retour", root_path %>
</div>
<div id="map" style="width:100%; height: 100vh;"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      data-markers="<%= @markers.to_json %>">
</div>

app/views/challenges/score.html.erb
<div class="main">
 <div class="lottie-bg">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <lottie-player src="https://assets6.lottiefiles.com/packages/lf20_9Y9DIQ.json" speed="0.5"  style= "left:0 ; right: 0; position:absolute"  autoplay></lottie-player>
 </div>
 <div class="banner-custom">
    <img src='https://cdn.pixabay.com/photo/2017/01/18/10/43/banner-1989514_1280.png' alt=''>
    <div class="banner-back">
      <%= link_to "retour", url_for(:back) %>
    </div>
  </div>
  <div class="box-avatar">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <lottie-player src="https://assets5.lottiefiles.com/packages/lf20_xldzoar8.json" speed="1"  class= "avatar border-red" loop  autoplay></lottie-player>
  </div>


  <h3>Score <%= @challenge.mission.name %></h3>
  <p style="font-size:17px;margin-top:20px;font-weight:bold;color:#FC635B">Bravo! Vous avez débloqué l'endroit secret et terminé la mission!</p>


  <div class="score-box">

    <div class="score-list" id="mission_done">
      <p class="score-list-title">Mission achevée:</p>
      <p><%= @challenge.calculate_score[:score_end_mission] %> pts</p>
      <p class="score-list-points">
        <% if @challenge.calculate_score[:mission_done] %>
          + <%= @challenge.calculate_score[:mission_points]  %> pts
        <% else %>
          0 pts
        <% end %>
      </p>
    </div>


    <div class="score-list" id="question_answered">
      <p class="score-list-title"> Questions répondues:</p>
      <p>
        <%= @challenge.calculate_score[:question_answered] %>
        x
        <%= @challenge.calculate_score[:question_points] %> pts
      </p>
      <p class="score-list-points"> + <%= @challenge.calculate_score[:score_questions] %> pts</p>

    </div>

    <div class="score-list" id="guess_false">
      <p class="score-list-title"> Mauvaises réponses:</p>
      <p>
        <%= @challenge.calculate_score[:question_guess] - @challenge.calculate_score[:question_answered]  %>
        x
        <%= @challenge.calculate_score[:guess_malus] %> pts
      </p>
      <p class="score-list-points"> <%= @challenge.calculate_score[:score_guess] %> pts</p>
    </div>

    <div class="score-list" id="final_guess_false">
      <p class="score-list-title">Mauvais lieu secret:</p>
        <p>
          <%= @challenge.calculate_score[:final_guess]  %>
          x
          <%= @challenge.calculate_score[:final_guess_malus] %> pts
        </p>
        <p class="score-list-points"><%= @challenge.calculate_score[:score_final_guess] %> pts</p>
    </div>

    <div class="score-list" id="bonus">
      <p class="score-list-title">Bonus difficulté: </p>
      <p>
        <%= @challenge.calculate_score[:mission_difficulty] %>
        <%= (@challenge.calculate_score[:bonus] * 100).to_i %>%
      </p>
      <p class="score-list-points"><%= @challenge.calculate_score[:bonus_points] %> pts</p>
    </div>

    <div class="score-list" id="multiplier">
    </div>

    <div id="final-score-box">
    <h2 id="final-score"><p style="font-size:20px;">Total de la mission:</p> <%= @challenge.calculate_score[:final_score] %> pts</h2>
    </div>

  </div>
</div>

app/views/challenges/show.html.erb
<div class="wrapper-challenge-show d-flex flex-column justify-content-between">
  <header class="header-challenge-show">
    <div class="banner-custom">
      <img src='https://cdn.pixabay.com/photo/2017/01/18/10/43/banner-1989514_1280.png' alt=''>
      <div class="banner-back">
        <%= link_to "retour", missions_path%>
      </div>
    </div>
    <div class="box-avatar">
      <%= link_to challenge_map_path(@challenge) do %>
        <lottie-player src="https://assets7.lottiefiles.com/packages/lf20_svy4ivvy.json" speed="1" class= "loading avatar border-red" loop autoplay></lottie-player>
      <% end %>
    </div>

 <%if @challenge.mission.clues.count == @challenge.challenge_questions.where(status: true).count %>
      <div style="text-align:center">
      <p>Rendez-vous sur le lieu secret en vous aidant des indices et validez-le en appuyant sur le bouton!</p>
        <button class="mb-2 btn-mission" id="local-validation" data-challengeId=<%= @challenge.id %>>J'ai trouvé!</button>
      </div>
 <%else%>
    <div class="text-map">
      <i class="map-arrow fas fa-sort-up"></i>
      <h2>Ouvrir la map</h2>
      <p>Pour débloquer les indices, répondez aux différentes questions disponibles sur la Map!</p>
    </div>
  <% end %>
  </header>

<div class="show-box">
<ul class="list-clues">
<% @challenge.mission.clues.each_with_index do |clue, index|%>
        <% if index < @challenge.challenge_questions.where(status: true).count %>
        <li class="row-show-unlocked fade-in-right" style="display:flex;align-items: center;">
              <i class="fas fa-unlock-alt p-2"></i>
              <p class="text-clue"><%= clue.description%></p>
          </li>
        <% else %>
          <li class="row-show-locked">
              <i class="fas fa-lock p-2"></i>
              <div class="clue-text">Indice bloqué</div>
          </li>
        <% end %>
    <% end %>
</ul>
</div>

</div>