config/routes.rb
Rails.application.routes.draw do
  get 'tuto/show'
  devise_for :users
  root to: 'users#playground'
  resources :users, only: [:index] do
    collection do
      get :playground
    end
  end

  resources :missions, only: [:index, :show] do
    resources :challenges, only: [:create]
  end

  resources :challenges, only: [:show] do
    post 'validate', as: :validate
    resources :questions do
      post 'validate', as: :validate, to: 'challenge_questions#validate'
      get 'new', to: 'challenge_questions#new'
    end
    get 'map', to: 'challenges#map'
    # post 'map', as: :validate, to: 'challenge_questions#validate'
    get 'score', to: 'challenges#score'
  end

  get 'map_all_challenges', to: 'challenges#map_all_challenges'

  # Route for Treasuremapp tuto
  get 'tuto/description_treasurmapp', to: 'tuto#description'
end

app/models/mission.rb
class Mission < ApplicationRecord
  has_many :challenges
  has_many :questions
  has_many :clues
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def index
    @missions = Mission.all
  end

  def show
    @mission = Mission.find(params[:id])
  end
end

app/views/missions/index.html.erb
<div class="main">

 <div class="banner-custom">
    <img src='https://cdn.pixabay.com/photo/2017/01/18/10/43/banner-1989514_1280.png' alt=''>
    <div class="banner-back">
      <%= link_to "retour", url_for(:back) %>
    </div>
  </div>
  <div class="box-avatar">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <lottie-player src="https://assets9.lottiefiles.com/packages/lf20_jcyhxkau.json" speed="1"  class= "avatar border-red" loop  autoplay></lottie-player>
  </div>

  <h1>Nouvelles Missions</h1>



  <% @missions.each do |mission|%>
    <% if Challenge.find_by(mission: mission, user: current_user).nil? %>
      <div class="index-card">
        <div class="index-photo">
          <%= image_tag mission.photo_url, alt: "Le Wagon" %>
        </div>
        <div class="index-card-infos">
          <div class="index-card-infos-text">
            <h5><%= mission.name %></h5>
            <div>
              <p>📍 <%= mission.city %> </p>
              <p>🏋️‍♀️ <%= mission.difficulty %></p>
            </div>
          </div>
          <div class="btn-red index-card-button"><%= link_to 'Découvrir', mission_path(mission)%></div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/missions/show.html.erb
<div class="main">
  <div class="box-distribute">
    <div class="banner-custom">
      <img src='https://cdn.pixabay.com/photo/2017/01/18/10/43/banner-1989514_1280.png' alt='Background Picture'>
      <div class="banner-back">
        <%= link_to "retour", missions_path%>
      </div>
    </div>
    <div class="box-avatar">
      <img class= "avatar border-red" src=<%=@mission.photo_url%>>
    </div>
    <div class="title-mission">
      <h2><%=@mission.name%></h2>
    </div>
  </div>

  <div class="box-distribute">
    <div class="mission-icon-box">
      <div class="row p-0">
        <div class="col-6" style="text-align:center">
          <div>
            <div class="lotti-container">
              <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
              <lottie-player src="https://assets1.lottiefiles.com/private_files/lf30_hvkvxnt3.json"   speed="1"  class= "lotti-avatar"  loop  autoplay></lottie-player>
            </div>
            <%=@mission.category%>
          </div>
          <div>
            <div class="lotti-container">
              <lottie-player src="https://assets3.lottiefiles.com/packages/lf20_4yofoa5q.json"  speed="1"  class= "lotti-avatar"  loop  autoplay></lottie-player>
            </div>
            <%=@mission.time%>
          </div>
        </div>
        <div class="col-6" style="text-align:center">
          <div>
            <div class="lotti-container">
              <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.js"></script>
  <dotlottie-player src="https://assets6.lottiefiles.com/dotlotties/dlf10_p1ftxhgu.lottie"  speed="1" class= "lotti-avatar"  loop autoplay></dotlottie-player>
            </div>
            <%=@mission.difficulty%>
          </div>
        <div>
          <div class="lotti-container">
            <lottie-player src="https://assets8.lottiefiles.com/packages/lf20_4xw7yai4.json"  speed="1"  class= "lotti-avatar"  loop  autoplay></lottie-player>
          </div>
          <%=@mission.city%>
          </div>
        </div>

        <div class="text-mission">
          <%=@mission.description%>
        </div>
      </div>
    </div>
  </div>

  <div class="box-distribute" style="margin-bottom: 20px">
    <%= link_to "Commencer la mission", mission_challenges_path(@mission), method: 'post', class:'btn-mission' %>
  </div>

</div>